### PR TITLE
Adds head and some other useful functions

### PR DESCRIPTION
**Pull request by mikesol**

### CODE REVIEW

**Comment by mikesol** [comment]
This is ready for review now, thanks!
I'm using this branch in `rito` for Instanced Meshes and it's working nicely. I haven't noticed any difference between `Sparse.Read` and `Sparse.Write` performance-wise, but nothing I'm doing is hitting a case where either would distinguish it self.

**Review by sigma-andex — APPROVED** [review]
Awesome, that looks amazing :-)

**Comment by sigma-andex** [comment]
@mikesol there seems to be a conflict somewhere, but I fail to see where

**Comment by mikesol** [comment]
> @mikesol there seems to be a conflict somewhere, but I fail to see where

I looked around but I couldn't find a conflict. Is it flagged somewhere on the PR page?

**Comment by sigma-andex** [comment]
Yes I cannot merge it, it says `This branch cannot be rebased due to conflicts`

**Comment by sigma-andex** [comment]
Ok whatever, did a merge commit

**Comment by mikesol** [comment]
Apologies for the crappy commit messages - usually I squash and merge stuff and do a proper commit message for the squashing.

**Pull request merged**
